
set MATLAB=D:\MATLAB\R2022a

"%MATLAB%\bin\%MATLAB_WIN_VER%\gmake" -f TestPilAdc_ca.mk  OPTS="-DCA_CHECK_FLOATING_POINT_ENABLED=1 -DPROFILING_DEFINE_UINT64_TIMER_TYPE -DCA_CHECK_LONG_LONG_ENABLED=0 -DCA_CHECK_DYNAMIC_MEMORY=0 -DCA_CHECK_DAZ_ENABLED=1"
